#ifndef PERIPHERAL_GPIO_H
#define PERIPHERAL_GPIO_H

//LED PIN
#define GREEN_PIN GPIOF
#define GREEN_GPIO_PORT GPIO_PIN_14
#define RED_PIN GPIOE
#define RED_GPIO_PORT GPIO_PIN_7

//EXIT
#define MPU_INT GPIO_PIN_1 //PE1
#define IST_INT GPIO_PIN_3 //PE3

#endif
